permalink: "/:year/:month/:day/:title/"
exclude: ["README.markdown"]
lsi: false
safe: true

baseurl: ""
#url: "//irssi-import.github.io"

title: Irssi
project: The Irssi Project
description: The Client of the Future
name: Irssi Core Team
email: staff@irssi.org

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 8
paginate_path: "news/:num/"

collections:
  articles:
    output: true
    permalink: "/articles/:title/"
